ALTER TABLE JobConfig DROP FOREIGN KEY `fk_vm_jc_sci`;
ALTER TABLE JobConfig DROP FOREIGN KEY `fk_vm_jc_sco`;

ALTER TABLE JobConfig MODIFY COLUMN DataInSourceConfigID  VARCHAR(256) NULL;
ALTER TABLE JobConfig MODIFY COLUMN DataOutSourceConfigID VARCHAR(256) NULL;