ALTER TABLE Device ADD COLUMN CloudSourceID VARCHAR(100) NULL AFTER SourceID;
ALTER TABLE `Device` ADD CONSTRAINT `fk_vm_d_csid` FOREIGN KEY (`CloudSourceID`) REFERENCES `Source` (`ID`);
ALTER TABLE Device MODIFY COLUMN SourceID VARCHAR(100) NULL;


ALTER TABLE Device DROP FOREIGN KEY fk_vm_d_ag;
ALTER TABLE AssetGroup DROP PRIMARY KEY;
ALTER TABLE AssetGroup ADD CONSTRAINT PRIMARY KEY (OrganizationID, GroupID, ScannerSourceID);