ALTER TABLE Device ADD COLUMN Region VARCHAR(100) NULL AFTER InstanceID;
ALTER TABLE Device ADD COLUMN SourceID VARCHAR(100) NOT NULL AFTER ID;
ALTER TABLE Device ADD COLUMN MAC VARCHAR(100) NULL AFTER IP;
ALTER TABLE Device ADD COLUMN HostName VARCHAR(500) NOT NULL AFTER MAC;
ALTER TABLE Device ADD COLUMN State VARCHAR(100) NULL AFTER AssetID;
Alter Table Device ADD COLUMN Updated DATETIME NULL;

CREATE TRIGGER DeviceUpdateTrigger BEFORE UPDATE ON `Device`
    FOR EACH ROW
        SET new.Updated = NOW();