ALTER TABLE `Detection` DROP FOREIGN KEY `fk_vm_det_d`;

ALTER TABLE Detection MODIFY COLUMN DeviceID VARCHAR(360) NOT NULL;
ALTER TABLE Device MODIFY COLUMN AssetID VARCHAR(360) NULL;

ALTER TABLE `Detection` ADD CONSTRAINT `fk_vm_det_d` FOREIGN KEY (`DeviceID`) REFERENCES `Device` (`AssetID`);